* reformated files and replaced tabs * replaced exit codes with more known and already used codes * replaced examples

diff --git a/wait_for b/wait_for
--- a/wait_for
+++ b/wait_for
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-host="127.0.0.1"
+host=""
 port=22
 delay=0
 proto="tcp"
@@ -14,156 +14,179 @@ go=0
 start_time=$(date +%s)
 
 die(){
-	local code=$1
-	shift
-	echo "$@"
-	exit $code
+   local code=$1
+   shift
+   echo "$@"
+   exit $code
 }
 
 usage(){
-	cat <<EOF
+   cat <<EOF
 NAME
-	wait_for - wait_for a host to be reachable
+   wait_for - wait_for a host to be reachable
 
 
 SYNOPSIS
 
-	wait_for [--option=value] [command]
+   wait_for ( [--option=value] | host )[command]
 
 
 DESCRIPTION
 
-		this command waits for a host:port to be reachable. It either executes a command directly or if no command is given it returns 0 or an error code. 
-		the first non option argument is recognized as the beginning of the command. The command has to go last.
-		wait_for needs at least 1 argument. Either --host or a command.
+   this command waits for a host:port to be reachable. It either executes a command directly or if no command is given it returns 0 or an error code.
+   the first non option argument is recognized as the beginning of the command. The command has to go last.
+   wait_for needs at least 1 argument. Either --host or a command.
 
 OPTIONS
 
-		--host=127.0.0.1   # A resolvable hostname or IP address to wait for Default is 127.0.0.1
-		--help             # Shows this help page
-		--sleep=1          # Number of seconds to sleep between checks. Default 1 seconds. Sleep has to be a only fraction of timeout.
-		--delay=0          # Number of seconds to wait before starting to poll. Default 0 seconds
-		--wait=0           # Number of seconds to wait after the host is reachable. Default  0 seconds
-		--timeout=300      # Maximum number of seconds to wait for, if run up it will force an error. Default 300 seconds. 
-				    Is only checked every --sleep seconds, so real timeout is only proximately --timeout
-		--port=22          # Port number to poll Default is 22 (ssh)
-		--proto=icmp       # Proto ICMP or TCP. If ICMP port will be ignored
+   --sleep=1          # Number of seconds to sleep between checks. Default 1 seconds. Sleep has to be a only fraction of timeout.
+   --delay=0          # Number of seconds to wait before starting to poll. Default 0 seconds
+   --wait=0           # Number of seconds to wait after the host is reachable. Default  0 seconds
+   --timeout=300      # Maximum number of seconds to wait for, if run up it will force an error. Default 300 seconds.
+             Is only checked every --sleep seconds, so real timeout is only proximately --timeout
+   --port=22          # Port number to poll Default is 22 (ssh)
+   --proto=icmp       # Proto ICMP or TCP. If ICMP port will be ignored
+   --help             # Shows this help page
+   --host=host        # A resolvable hostname or IP address to wait for.
 
 COMMAND
-		every non option argument is considered as beginning of the command wait_for is supposed to execute.
-		if no command is given wait_for returns an exit status code.
+
+   if --host is not give then the first argument is the host.
+   In any other case, every non option argument is  considered as beginning of the command wait_for is supposed to execute.
+   if no command is given "wait_for" just returns an exit status code after finishing.
 
 
 EXAMPLES
-		wait_for --host=myserver scp file  root@myserver:/folder/  || echo "Timeout. myserver not reachable"
-		wait_for --host=myserver ssh myserver reboot && echo "myserver is rebooting"
-		wait_for --host=myserver --port=80  &&  curl --HEAD myserver  || echo "My Server not reachable" 
-		pon dsl; wait_for --proto=icmp --wait=10 --host=dyndns.mydomain.com sudo /etc/firewall restart.
 
-		if wait_for --host=mad4milk.de;
-		then
-			scp stuff 
-			ssh "do stuff"
-			do more stuff
-		else
-			echo "can't do stuff"
-		fi	
+   wait_for myserver scp file root@myserver:/folder/  || echo "Timeout. myserver not reachable"
+        wait_for --port=80 myserver && curl --HEAD http://myserver/ && notify-send --hint string:sound-name:dialog-ok "Server back up"
+   wait_for --icmp --wait=300 my-super-secure-server && ssh my-super-secure-server systemctl restart start   # better not provoke fail2ban
+   pon dsl; wait_for --icmp --wait=10 --host=dyndns.mydomain.com sudo /etc/firewall restart.
+
+   if ./wait_for --mad4milk.de;
+   then
+      echo "do stuff"
+   else
+      case $? in
+         22) echo "invalid argument. can't do stuff";;
+         66) echo "timeout. can't do stuff";;
+         *)  echo "$? something unexpectet happend";;
+      esac
+   fi
 
 
 KNOWNBUGS
 
-		because I use a bash socket I can't control the timeout of said socket. I may add a netcat option.
-		Under some circumstances the there are additional 30 seconds of sleep (the socket timeout) every poll. 
-		This will reduce the poll rate and timeout will take longer. Up to 29 seconds. 
+   because I use a bash socket I can't control the timeout of said socket. I may add a netcat option.
+   Under some circumstances the there are additional 30 seconds of sleep (the socket timeout) every poll.
+   This will reduce the poll rate and timeout will take longer. Up to 29 seconds.
 
 
 EXIT STATUS
-		wait_for exits with 
-			0 on success
-			84 on connect timeout
-			92 invalid argument
-		or the return code of "command"
+
+   wait_for exits with ( from errno-base.h/errno.h taken from the linux kernel )
+      0 on success
+      22 invalid argument
+      62 time expired
+
+   or the return code of COMMAND
+
+ALTERNATIVES
+
+   If you're only looking for ssh/scp trying to connect until the ssh is reachable again you should take a
+   look into the ssh_config manpage."ConnectionAttempts" could be the option for you.
+
 
 EOF
 }
 
 until [[ "$@" == '' ]]
 do
-	param="${1//=*/}"
-	value="${1//*=/}"
-	case $param in
-		--help)
-			usage
-			exit 1
-			;;
-		--host)
-                        [[ "$value" == '' ]] && die 92 "--host has to be an IP or hostname"
+   param="${1//=*/}"
+   value="${1//*=/}"
+   case $param in
+      --help)
+         usage
+         exit 1
+         ;;
+      --host)
+                        [[ "$value" == '' ]] && die 22 "--host has to be an IP or hostname" # EINVAL /* Invalid argument */
                         go=1
                         host="$value"
                         ;;
                 --port)
-                        [[ "${value//[0-9a-zA-Z]/}" == '' ]] || die 92 "--port accepts a port number or a services name"
+                        [[ "${value//[0-9a-zA-Z]/}" == '' ]] || die 22 "--port accepts a port number or a services name" # EINVAL /* Invalid argument */
                         port="$value"
                         go=1
                         ;;
-		--delay)
-                        [[ "${value//[0-9]/}" == '' ]] || die 92 "--delay only accepts seconds"
+      --delay)
+                        [[ "${value//[0-9]/}" == '' ]] || die 22 "--delay only accepts seconds" # EINVAL /* Invalid argument */
                         delay="$value"
-			go=1
+         go=1
                         ;;
-		--sleep)
-			[[ "${value//[0-9]/}" == '' ]] || die 92 "--sleep only accepts seconds"
-			sleep_time="$value"
-			;;
-		--wait)
-                        [[ "${value//[0-9]/}" == '' ]] || die 92 "--sleep only accepts seconds"
+      --sleep)
+         [[ "${value//[0-9]/}" == '' ]] || die 22 "--sleep only accepts seconds" # EINVAL /* Invalid argument */
+         sleep_time="$value"
+         ;;
+      --wait)
+                        [[ "${value//[0-9]/}" == '' ]] || die 22 "--sleep only accepts seconds" # EINVAL /* Invalid argument */
                         wait_time="$value"
                         ;;
-		--timeout)
-			[[ "${value//[0-9]/}" == '' ]] || die 92 "--timeout only accepts seconds"
-			timeout="$value"
-			;;
-		--proto)
-			[[ "${value}" != 'tcp' && "${value}" != "icmp" ]] && die 92 "--proto only accepts tcp or icmp as a parameter"
-			proto="$value"
-			;;
-		*)
-			cmd="$@"
-			go=1
-			break
-			;;
-	esac
-	shift
+      --timeout)
+         [[ "${value//[0-9]/}" == '' ]] || die 22 "--timeout only accepts seconds" # EINVAL /* Invalid argument */
+         timeout="$value"
+         ;;
+      --proto)
+         [[ "${value}" != 'tcp' && "${value}" != "icmp" ]] && die 22 "--proto only accepts tcp or icmp as a parameter" # EINVAL /* Invalid argument */
+         proto="$value"
+         ;;
+      --icmp)
+         proto="icmp"
+         ;;
+      *)
+         if [[ "$host" == "" ]]; then
+            go=1
+            host=$1
+            shift
+            continue
+         fi
+         cmd="$@"
+         go=1
+         break
+         ;;
+   esac
+   shift
 done
 
 real_timeout=$((delay+timeout))
 
 check_timeout(){
-	if [[ $(($(date +%s)-start_time)) -gt $real_timeout ]];
-	then
-		timeouted=1
-		return 0
-	fi
-	return 1
+   if [[ $(($(date +%s)-start_time)) -gt $real_timeout ]];
+   then
+      timeouted=1
+      return 0
+   fi
+   return 1
 }
 
 
-if [[ $go -eq 1 ]]; 
+if [[ $go -eq 1 ]];
 then
-	sleep "$delay"
-	until check_timeout
-	do
-		if [[ "$proto" == "tcp" ]];
-		then
-			(echo -n "" > "/dev/$proto/$host/$port") >/dev/null 2>&1 && break
-		else
-			ping -q -W2 -c1 "$host" >/dev/null  && break
-		fi
-		sleep $sleep_time
-	done
-	sleep "$wait_time"
-	[[ $timeouted != 0 ]] && exit 84 
-	[[ "$cmd" == "" ]] && exit 0
-	[[ "$cmd" != "" ]] && eval "$@"
-fi	
+   sleep "$delay"
+   until check_timeout
+   do
+      if [[ "$proto" == "tcp" ]];
+      then
+         (echo -n "" > "/dev/$proto/$host/$port") >/dev/null 2>&1 && break
+      else
+         ping -q -W2 -c1 "$host" >/dev/null  && break
+         [[ $? > 1 ]] && die 101 "Network is unreachable" # ENETUNREACH  /* Network is unreachable */
+      fi
+      sleep $sleep_time
+   done
+   sleep "$wait_time"
+   [[ $timeouted != 0 ]] && exit 62 # ETIME /* Timer expired */
+   [[ "$cmd" == "" ]]    && exit  0 # success
+   [[ "$cmd" != "" ]]    && eval "$@"
+fi
 exit $status
